apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox
  namespace: argocd
  labels:
    tags.datadoghq.com/env: production
    tags.datadoghq.com/service: sandbox
    tags.datadoghq.com/version: v0.1.7
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    repoURL: 'https://github.com/aisrael/gitops'
    path: charts/sandbox/production
    targetRevision: main
    helm:
      releaseName: sandbox
      valueFiles:
        - vars/production.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
